# Generated by Django 4.0.8 on 2022-12-26 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Shop code can only be alphanumeric or underscore')], verbose_name='Shop Code')),
                ('name', models.CharField(max_length=50, verbose_name='Shop Name')),
            ],
            options={
                'ordering': ('code', 'name'),
            },
        ),
    ]
