# Generated by Django 4.0.8 on 2022-12-27 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$', 'Product code can only be alphanumeric or underscore')], verbose_name='Product Code')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Product Name')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Price')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.shop')),
            ],
            options={
                'ordering': ('code', 'name'),
            },
        ),
    ]
