# Generated by Django 4.0.8 on 2023-01-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_cartitem_cart_remove_cartitem_product_and_more'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='shop.address'),
            preserve_default=False,
        ),
    ]
