# Generated by Django 4.0.8 on 2022-12-27 06:01

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=67676, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Phone can only be numbers')], verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='ShopDetails',
        ),
    ]
