# Generated by Django 4.0.8 on 2022-12-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('shop', '0002_address_phone_address_uuid_delete_shopdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop.address')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
