# Generated by Django 4.0.8 on 2022-12-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopDetails',
        ),
    ]
