# Generated by Django 4.0.8 on 2022-12-26 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Store Owner'), ('manager', 'Store Manager'), ('shipper', 'Store Delivery')], default='shipper', max_length=20, verbose_name='Role')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.shop')),
            ],
            options={
                'ordering': ('role',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.ManyToManyField(blank=True, through='users.UserToShop', to='tenant.shop'),
        ),
        migrations.AddField(
            model_name='usertoshop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CurrentShopForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'shop'),
            },
        ),
    ]
